### ISSUE TITLE
move to toml

### ISSUE THREAD

**Issue by saltkid** [saltkid/tbg#27]
example yaml before:
```yaml
paths:
    - path: ~/pictures/wt_bg/right-uniform-0.1
      alignment: right
    - path: ~/pictures/wt_bg/center-uniform-0.1
    - path: ~/pictures/wt_bg/center-uniformToFill-0.1
      stretch: uniformToFill
interval: 30
profile: list-3
alignment: center
stretch: uniform
opacity: 0.1
```
example toml after:
```toml
interval = 30
profile = "list-3"
alignment = "center"
stretch = "uniform"
opacity = 0.1

[[paths]]
path = "~/pictures/wt_bg/right-uniform-0.1"
alignment = "right"

[[paths]]
path = "~/pictures/wt_bg/center-uniform-0.1"

[[paths]]
path = "~/pictures/wt_bg/center-uniformToFill-0.1"
stretch = "uniformToFill"
```
